version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskvault
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-service:
    build:
      context: ./auth-service
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/taskvault
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: TaskVault
      KEYCLOAK_CLIENT_ID: auth-service
      KEYCLOAK_CLIENT_SECRET: your_keycloak_client_secret
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - keycloak

  user-service:
    build:
      context: ./user-service
    environment:
      PORT: 3001
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/taskvault
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  task-service:
    build:
      context: ./task-service
    environment:
      PORT: 3002
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/taskvault
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  event-service:
    build:
      context: ./event-service
    environment:
      PORT: 3003
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/taskvault
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - "3003:3003"
    depends_on:
      - postgres
      - rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    ports:
      - "8080:8080"

volumes:
  pgdata:



## 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 